name: funcle
channels:
  - conda-forge
dependencies:
  - python = 3.7
  - scipy > 1.0
  - numpy
  - matplotlib
  - flake8
  - sphinx
  - cython
  - sphinxcontrib-bibtex
  - pint
  - cvxopt
  - coverage
  - graphviz
  - pylint
